apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine:latest
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/source/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: python:3.9
      workingDir: /workspace/source
      script: |
        #!/bin/bash
        pip install -r requirements.txt
        pip install nose
        nosetests
